[build]
  base = "frontend"
  publish = "frontend/out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://datavibe.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200